name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-webserver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker image for Webserver
        run: |
          docker build -t gjorgdy/baseline-web:latest -f ./WebServer/Dockerfile .
          docker push gjorgdy/baseline-web:latest

  build-api-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker image for API Server
        run: |
          docker build -t gjorgdy/baseline-api:latest -f ./ApiServer/Dockerfile .
          docker push gjorgdy/baseline-api:latest
